### ISSUE TITLE
question regarding abstractions over pwhash, secretbox, AEAD

### ISSUE THREAD

**Issue by d-p-y** [vlang/libsodium#12]
Hi,
I've followed official libsodium docs and implemented typesafe abstractions over those functions. Goal was to prevent abuse and get better error checking.
It depends on PR https://github.com/vlang/libsodium/pull/11 
You can find them in following branch https://github.com/d-p-y/libsodium/tree/extensions
Question: would you be interested in upstreaming those changes into vlang/libsodium in some form?

**Comment by medvednikov** [comment]
hi

of course, this is great stuff! I'll merge it

great work!

**Comment by d-p-y** [comment]
thanks :) I reworked it and created PR then
