### ISSUE TITLE
example for asymmetric encryption would be nice

### ISSUE THREAD

**Issue by despiegk** [vlang/libsodium#2]
think https://libsodium.gitbook.io/doc/public-key_cryptography/authenticated_encryption can be used as example

in python there are good examples as well
https://pynacl.readthedocs.io/en/latest/public/#nacl-public-box

purpose is to encrypt with public key of destination
destination person uses private key to decrypt

Curve25519 should be the std

**Comment by medvednikov** [comment]
```
// Public-key cryptography
key_alice := new_private_key()
key_bob := new_private_key()
bob_box := new_box(key_bob, key_alice.public_key)
encrypted := bob_box.encrypt_string('hello')
alice_box := new_box(key_alice, key_bob.public_key)
decrypted := alice_box.decrypt_string(encrypted)
println(decrypted)
assert decrypted == 'hello'```
