### ISSUE TITLE
Please make nonce configurable

### ISSUE THREAD

**Issue by a1730** [vlang/libsodium#6]
I use currently use [smallstep cli](https://github.com/smallstep/cli) for secretbox encryption and I thought it would be nice to rewrite the command in V. 
The code was very easy to write. However, current V secretbox implementation does not expose the nonce so it is not possible to inter-operate with smallstep cli, or even with another V process.

My workaround was to to make nonce ```pub mut``` in smallstep.v, and change the type from current [24]byte to []byte. I now pass the nonce on the command line to both smallstep and my sbox cli.

Thank you for porting libsodium to V!

**Comment by medvednikov** [comment]
Thanks, will do!

You can also try to submit a PR, this should be a relatively simple change.
